distro/pkg/rpm: require setuptools on suse
Otherwise:

Traceback (most recent call last):
  File "/builddir/build/BUILD/knot-resolver-6.0.1.dev90+5003e3/manager/setup.py", line 2, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'